AWSTemplateFormatVersion : "2010-09-09"
Description : "AWS CloudFormation Cross-Stack Reference Sample Template: Demonstrates how to reference resources from a different stack. This template provisions an EC2 instance in an EC2 Security Group provisioned in a different stack. **WARNING** This template creates an Amazon EC2 instance. You will be billed for the AWS resources used if you create a stack from this template.",
Parameters: 
  NetworkStackName:
    Description: "Name of an active CloudFormation stack that contains the networking resources, such as subnet and security group, that will be used in this stack"
    Type: "String",
    MinLength : 1,
    MaxLength : 255,
    AllowedPattern : "^[a-zA-Z][-a-zA-Z0-9]*$",
    Default : "crossNetwork"
  LastestAmiId: AWSTemplateFormatVersion : "2010-09-09"
Description : "AWS CloudFormation Cross-Stack Reference Sample Template: Demonstrates how to reference resources from a different stack. This template provisions an EC2 instance in an EC2 Security Group provisioned in a different stack."
Parameters: 
  NetworkStackName:
    Description: "Name of an active CloudFormation stack that contains the networking resources, such as subnet and security group, that will be used in this stack"
    Type: "String"
    MinLength : 1
    MaxLength : 255
    AllowedPattern : "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default : "crossNetwork"
  LastestAmiId: 
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: "AMI for EC2"
    Default: "/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2"

Resources:
  MyWebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LastestAmiId
      NetworkInterfaces:
        - GroupSet: 
            - Fn::ImportValue:
                Fn::Sub: "${NetworkStackName}-SecurityGroupID"
          AssociatePublicIpAddress: true
          DeviceIndex: "0"
          DeleteOnTermination: true
          SubnetId: 
            Fn::ImportValue:
              Fn::Sub: "${NetworkStackName}-SubnetID"
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: "AMI for EC2"
    Default: "/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2"

Resources:
  MyWebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LastestAmiId
    NetworkInterfaces:
      - GroupSet: Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-SecurityGroupID"
        AssociatePublicIpAddress: true
        DeviceIndex: "0"
        DeleteOnTermination: true
        SubnetId: Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-SubnetID"