AWSTemplateFormatVersion : "2010-09-09"
Description: S3 Same Account CRR
Parameters:
  SourceBucketName:
    Description: Source Bucket Name
    Type: String
    Default: 'yang-source-bucket-123321'
  DestinationBucketName:
    Description: Destination Bucket Name
    Type: String
    Default: 'yang-destination-bucket-123321'

Resources:
  SourceS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
          Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt 
          - S3ReplicationRole
          - Arn
        Rules:
          - Destination:
              StorageClass: STANDARD
              Bucket: !GetAtt 
                - DestinationS3
                - Arn
            Status: Enabled
        # If Different region
            #       - !Join
            # - '-'
            # - - !Ref 'AWS::Region'
            #   - !Ref 'AWS::StackName'
            #   - replicationbucket

  DestinationS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DestinationBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
          Status: Enabled

  SourceS3BucketPolicy:  
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SourceS3
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Action: ["s3:GetObject"]
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref SourceS3
                - /*
            Principal: "*"

  DestinationS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DestinationS3
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Action: ["s3:GetObject"]
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref DestinationS3
                - /*
            Principal: "*"

  ################################
  ### IAM Role for replication ###
  ################################
  S3ReplicationRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "S3ReplicationRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "s3.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "S3ReplicationPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Permissions for source bucket
              - Effect: "Allow"
                Action:
                  - "s3:GetReplicationConfiguration"
                  - "s3:ListBucket"
                Resource: !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref SourceBucketName
                    - /*
              - Effect: "Allow"
                Action:
                  - "s3:GetObjectVersionForReplication"
                  - "s3:GetObjectVersionAcl"
                  - "s3:GetObjectVersionTagging"
                Resource: !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref SourceBucketName
                    - /*
              # Permissions for destination bucket
              - Effect: "Allow"
                Action:
                  - "s3:ReplicateObject"
                  - "s3:ReplicateDelete"
                  - "s3:ReplicateTags"
                Resource: !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref DestinationBucketName
                    - /*
      


  