AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.16.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

Outputs:
  BucketName:
    Value: !Ref MyVPC
    Description: "The resource ID of the VPC created"
