AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment: 
    Type: String
    Description: Environment Type
    Default: "dev"
    AllowedValues:
      - "dev"
      - "prod"
  EC2InstanceType:
    Type: String
    Description: Available EC2 Instance Type
    Default: "t2.micro"
    AllowedValues: 
      - t2.micro
      - t3.micro
Resources:
  NestedVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://mycloudformationtemplatebucket.s3.us-east-1.amazonaws.com/nestedVPC.yml"
      Parameters:
        EnvType: !Ref Environment
  NestedEC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NestedVPCStack
    Properties:
      TemplateURL: "https://mycloudformationtemplatebucket.s3.us-east-1.amazonaws.com/nestedEC2.yml"
      Parameters:
        EnvType: !Ref Environment
        MyEC2InstanceType: !Ref EC2InstanceType
        SubnetID: !GetAtt [NestedVPCStack, Outputs.PublicSubnet1ID] # This is how to get parameter from other nested stack